version: '3'
services:
    jenkins:
        image: jenkins/jenkins:lts
        container_name: jenkins
        ports:
            - '8080:8080' # Port cho giao diện web của Jenkins
            - '50000:50000'
        volumes:
            - jenkins_data:/var/jenkins_home # Volume để lưu trữ dữ liệu của Jenkins

    # ngrok:
    #     image: ngrok/ngrok:latest
    #     network_mode: 'host' # Sử dụng mạng của máy chủ, giúp kết nối trực tiếp vào cổng 8080
    #     container_name: ngrok
    #     environment:
    #         - NGROK_AUTHTOKEN=2mEc9vpfhUvE90LtokNeKWKVLyh_7RGDrqPVJNuCnXvNFm7JM
    #     command: http 8080 # Kết nối tới Jenkins thông qua cổng 8080
    #     tty: true

volumes:
    jenkins_data:
